# Generated by Django 4.0.6 on 2022-07-07 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_of_publication']},
        ),
        migrations.AlterModelOptions(
            name='blog_comment',
            options={'ordering': ['post_date']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(help_text='Enter your blog', max_length=15000),
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='blog_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
